name: Lint and build the documentation

# see https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner
# for artifact handling and SBOM: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

on:
  push:
  #pull_request: # Not necessary, as it is already been executed on push
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  lint_content_in_repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
        cache: 'pip' # caching pip dependencies
    - name: print versions for debugging
      run: python --version ; pip --version ; whoami ; pwd
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install docutils sphinx-lint vale
    - name: Lint the project with sphinx-lint
      run: |
        sphinx-lint
    - name: Lint the project with vale
      uses: errata-ai/vale-action@v2.1.1
      with:
        # github-pr-check, github-pr-review, github-check
        reporter: github-check
        fail_on_error: false


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
        cache: 'pip' # caching pip dependencies
    - name: print versions for debugging
      run: python --version ; pip --version ; whoami ; pwd
    - name: Install graphviz & default-jdk
      run: |
        sudo apt-get update
        sudo apt-get upgrade --yes
        sudo apt-get install graphviz default-jdk
        sudo apt-get upgrade --yes
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install -r ./docs/requirements.txt
    - name: Render the documentation
      run: >
        sphinx-build
        -b html ./docs ./public
        -vv
        --jobs=auto
        --show-traceback
        --fail-on-warning
        --keep-going
    - name: Archive sphinx public folder
      uses: actions/upload-artifact@v4
      with:
        name: sphinx-public
        path: |
          ./public/


  # lint final sphinx html files
  lint_final_html_files:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download sphinx public folder
        uses: actions/download-artifact@v4
        with:
          name: sphinx-public
          path: ./public/
      - name: copy .vale.ini from static part to root folder
        run: |
          cp ./public/_static/vale_for_final_html.ini ./.vale.ini
      - name: Lint the html files with vale
        uses: errata-ai/vale-action@v2.1.1
        with:
          # github-pr-check, github-pr-review, github-check
          reporter: github-check
          files: ./public/


  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download sphinx public folder
        uses: actions/download-artifact@v4
        with:
          name: sphinx-public
          path: ./public/
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
